name: Preview Android app

on:
  pull_request:
    branches:
      - preview
    paths:
      - 'preview/v*'

jobs:
  build:
    type: build
    params:
      platform: android
      profile: preview
