name: Release Android app

on:
  pull_request:
    branches:
      - main
    paths:
      - 'release/v*'

jobs:
  build:
    type: build
    params:
      platform: android
      profile: production
